name: weathify
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

#
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  material_floating_search_bar_2: ^0.5.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.14

  # geolocator: ^10.1.0
  geolocator: ^7.7.1
  geocoding: ^3.0.0

  flutter_cache_manager: ^3.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  loading_animation_widget: ^1.2.0+4
  handy_window: ^0.4.0
  stretchy_header: ^2.0.0


  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1

dependency_overrides:
  geolocator_android:
    hosted:
      name: geolocator_android
      url: https://hanntech-gmbh.gitlab.io/free2pass/flutter-geolocator-floss

flutter_launcher_icons:
  image_path_android: "assets/icons/Overmorrow_white_circle.png"
  image_path_ios: "assets/icons/Overmorrow_white_classic.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
  image_path: "assets/icons/Overmorrow_white_classic.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/Overmorrow_white_classic.png"
    background_color: "#b1c4cf"
    theme_color: "#b1c4cf"
  windows:
    generate: true
    image_path: "assets/icons/Overmorrow_white_classic.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/Overmorrow_white_classic.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

#
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/backdrops/
    - assets/icons/


